### ISSUE TITLE
Something missing - what does it mean ...

### ISSUE THREAD

**Issue by KNXfriend** [htool/signalk-naviop-plugin#1]
Loaded the plugin into my new setup signal k server and get this:

Status: Failed to start: Cannot find module 'lodash' Require stack: - /data/conf/signalk/node_modules/signalk-naviop-plugin/canboatjs/lib/fromPgn.js - /data/conf/signalk/node_modules/signalk-naviop-plugin/canboatjs/index.js - /data/conf/signalk/node_modules/signalk-naviop-plugin/index.js - /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js - /usr/lib/node_modules/signalk-server/lib/interfaces/index.js - /usr/lib/node_modules/signalk-server/lib/index.js - /usr/lib/node_modules/signalk-server/bin/signalk-server

Something is missing, but from where it should come?

**Comment by KNXfriend** [comment]
Found the lodash utility and installed it, but the above message remains.
$ npm i -g npm
$ npm i --save lodash
Would love to use this plugin, but for me many questions remain.
I there any possibility to discuss directly?

**Comment by htool** [comment]
Hi,
the plugin is in a messy state due to some rework.
I'm looking to see if I can get it back working for the season.
Most SignalK developers are on Slack: signalk-dev.slack.com

**Comment by htool** [comment]
I'm making good progress.
I expect to be able to release a version that's using the new simpleCan logic which should fix the whole missing dependencies issue.

**Comment by htool** [comment]
Getting close: https://youtu.be/h9i_ZxPWVRw
I'm waiting for a small pgns.json fix which is needed for the plugin to be recognised by the MFD.

**Comment by htool** [comment]
Can you try the latest version?

**Comment by KNXfriend** [comment]
Hello Hans!

Thank you for the fast response and your effort!
Now the plugin works in the SignalK Server without error messages in the
plugin config area and I see after the fresh start a Naviop AT30 Gateway
on the N2K network.

But then, something goes wrong. The MFD shows all states still red.

What I have done:
Created a loopse.xml with the navigon tool and installed it on the MFD.

Updated your plugin to V0.9.


Best regards
Nils


Further information, what I could collect:


Mar 11 08:39:38 TypeError: Cannot read property 'switches' of undefined
at Timeout.sendUpdate [as _onTimeout]
(/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:399:42)
at listOnTimeout (internal/timers.js:557:17) at processTimers
(internal/timers.js:500:7)

Seems that this even stops the plugin so far, that it disappears out of
the device list on the N2K network.
Seems that this was, because I changed the bank parameter to something != 1
Back to value 1, I don´t see the message above in the server log anymore
and so far the N2K entry remains.



I see in the server log now a lot of:

Mar 11 09:07:53 ReferenceError: deviceAddress is not defined at
/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:427:64 at
Array.forEach (<anonymous>) at Timeout.sendUpdate [as _onTimeout]
(/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:426:17)
at listOnTimeout (internal/timers.js:557:17) at processTimers
(internal/timers.js:500:7)


And I see now updates in the SignalK databrowser, when I switch at the
MFD, but the states at the MFD stays red.

Switching the button shows the folloing in the log:

Mar 11 09:22:53 2023-03-11T09:22:53.275Z signalk-naviop-plugin Received
packet msg:
{"canId":233644044,"prio":3,"src":12,"dst":32,"pgn":126208,"timestamp":"2023-03-11T09:22:53.267Z","input":[],"fields":{"Function
Code":"Command","PGN":127500,"Priority":"Leave priority unchanged","# of
Parameters":2,"list":[{"Parameter":2,"Value":0},{"Parameter":3,"Value":1},{"Parameter":0},{"Parameter":0},{"Parameter":0},{"Parameter":0}]},"description":"NMEA
- Command group function"}
Mar 11 09:22:53 2023-03-11T09:22:53.278Z signalk-naviop-plugin
n2k.fields.list:
[{"Parameter":2,"Value":0},{"Parameter":3,"Value":1},{"Parameter":0},{"Parameter":0},{"Parameter":0},{"Parameter":0}]

Mar 11 09:22:53 2023-03-11T09:22:53.280Z signalk-naviop-plugin instance:
1 state: 1
Mar 11 09:22:53 2023-03-11T09:22:53.282Z signalk-naviop-plugin Digital
switching command 126208 Instance 1 -> 1]
Mar 11 09:22:53 2023-03-11T09:22:53.286Z signalk-naviop-plugin
digiSwitch:
{"1":{"switches":{"1":{"path":"electrical.naviop.switches.1.state","state":0},"2":{"path":"electrical.naviop.switches.2.state","state":0},"3":{"path":"electrical.naviop.switches.3.state","state":0},"4":{"path":"electrical.naviop.switches.4.state","state":0},"5":{"path":"electrical.naviop.switches.5.state","state":0},"6":{"path":"electrical.naviop.switches.6.state","state":0},"7":{"path":"electrical.naviop.switches.7.state","state":0},"8":{"path":"electrical.naviop.switches.8.state","state":0}},"fuses":{"1":{"path":"electrical.naviop.fuses.1.state","state":0},"2":{"path":"electrical.naviop.fuses.2.state","state":0},"3":{"path":"electrical.naviop.fuses.3.state","state":0},"4":{"path":"electrical.naviop.fuses.4.state","state":0},"5":{"path":"electrical.naviop.fuses.5.state","state":0},"6":{"path":"electrical.naviop.fuses.6.state","state":0},"7":{"path":"electrical.naviop.fuses.7.state","state":0},"8":{"path":"electrical.naviop.fuses.8.state","state":0}}}}
Mar 11 09:22:53 2023-03-11T09:22:53.289Z signalk-naviop-plugin Updating
digiSwitch[1].switches[1].state to 1
Mar 11 09:22:53 2023-03-11T09:22:53.291Z signalk-naviop-plugin update:
{"updates":[{"values":[{"path":"electrical.naviop.switches.1.state","value":1}]}]}
Mar 11 09:22:53 2023-03-11T09:22:53.302Z signalk-naviop-plugin
handleUpdate: electrical.naviop.switches.1.state -> 1
Mar 11 09:22:53 2023-03-11T09:22:53.305Z signalk-naviop-plugin
updatePathState: electrical.naviop.switches.1.state to 1
Mar 11 09:22:53 2023-03-11T09:22:53.307Z signalk-naviop-plugin Checking
switches deviceObject:
{"1":{"path":"electrical.naviop.switches.1.state","state":1},"2":{"path":"electrical.naviop.switches.2.state","state":0},"3":{"path":"electrical.naviop.switches.3.state","state":0},"4":{"path":"electrical.naviop.switches.4.state","state":0},"5":{"path":"electrical.naviop.switches.5.state","state":0},"6":{"path":"electrical.naviop.switches.6.state","state":0},"7":{"path":"electrical.naviop.switches.7.state","state":0},"8":{"path":"electrical.naviop.switches.8.state","state":0}}
Mar 11 09:22:53 2023-03-11T09:22:53.309Z signalk-naviop-plugin Checking
switches 1: {"path":"electrical.naviop.switches.1.state","state":1}
Mar 11 09:22:53 2023-03-11T09:22:53.311Z signalk-naviop-plugin Checking
electrical.naviop.switches.1.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.313Z signalk-naviop-plugin
updatePathState: electrical.naviop.switches.1.state in
{"path":"electrical.naviop.switches.1.state","state":1}
Mar 11 09:22:53 2023-03-11T09:22:53.315Z signalk-naviop-plugin Checking
switches 2: {"path":"electrical.naviop.switches.2.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.317Z signalk-naviop-plugin Checking
electrical.naviop.switches.2.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.319Z signalk-naviop-plugin Checking
switches 3: {"path":"electrical.naviop.switches.3.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.321Z signalk-naviop-plugin Checking
electrical.naviop.switches.3.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.323Z signalk-naviop-plugin Checking
switches 4: {"path":"electrical.naviop.switches.4.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.325Z signalk-naviop-plugin Checking
electrical.naviop.switches.4.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.327Z signalk-naviop-plugin Checking
switches 5: {"path":"electrical.naviop.switches.5.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.338Z signalk-naviop-plugin Checking
electrical.naviop.switches.5.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.340Z signalk-naviop-plugin Checking
switches 6: {"path":"electrical.naviop.switches.6.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.342Z signalk-naviop-plugin Checking
electrical.naviop.switches.6.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.344Z signalk-naviop-plugin Checking
switches 7: {"path":"electrical.naviop.switches.7.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.346Z signalk-naviop-plugin Checking
electrical.naviop.switches.7.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.348Z signalk-naviop-plugin Checking
switches 8: {"path":"electrical.naviop.switches.8.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.350Z signalk-naviop-plugin Checking
electrical.naviop.switches.8.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.352Z signalk-naviop-plugin Checking
fuses deviceObject:
{"1":{"path":"electrical.naviop.fuses.1.state","state":0},"2":{"path":"electrical.naviop.fuses.2.state","state":0},"3":{"path":"electrical.naviop.fuses.3.state","state":0},"4":{"path":"electrical.naviop.fuses.4.state","state":0},"5":{"path":"electrical.naviop.fuses.5.state","state":0},"6":{"path":"electrical.naviop.fuses.6.state","state":0},"7":{"path":"electrical.naviop.fuses.7.state","state":0},"8":{"path":"electrical.naviop.fuses.8.state","state":0}}
Mar 11 09:22:53 2023-03-11T09:22:53.354Z signalk-naviop-plugin Checking
fuses 1: {"path":"electrical.naviop.fuses.1.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.356Z signalk-naviop-plugin Checking
electrical.naviop.fuses.1.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.358Z signalk-naviop-plugin Checking
fuses 2: {"path":"electrical.naviop.fuses.2.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.360Z signalk-naviop-plugin Checking
electrical.naviop.fuses.2.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.361Z signalk-naviop-plugin Checking
fuses 3: {"path":"electrical.naviop.fuses.3.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.363Z signalk-naviop-plugin Checking
electrical.naviop.fuses.3.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.365Z signalk-naviop-plugin Checking
fuses 4: {"path":"electrical.naviop.fuses.4.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.367Z signalk-naviop-plugin Checking
electrical.naviop.fuses.4.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.369Z signalk-naviop-plugin Checking
fuses 5: {"path":"electrical.naviop.fuses.5.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.371Z signalk-naviop-plugin Checking
electrical.naviop.fuses.5.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.373Z signalk-naviop-plugin Checking
fuses 6: {"path":"electrical.naviop.fuses.6.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.375Z signalk-naviop-plugin Checking
electrical.naviop.fuses.6.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.376Z signalk-naviop-plugin Checking
fuses 7: {"path":"electrical.naviop.fuses.7.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.378Z signalk-naviop-plugin Checking
electrical.naviop.fuses.7.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.380Z signalk-naviop-plugin Checking
fuses 8: {"path":"electrical.naviop.fuses.8.state","state":0}
Mar 11 09:22:53 2023-03-11T09:22:53.382Z signalk-naviop-plugin Checking
electrical.naviop.fuses.8.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:53 2023-03-11T09:22:53.387Z signalk-naviop-plugin Switch
states:
{"1":{"switches":{"1":{"path":"electrical.naviop.switches.1.state","state":1},"2":{"path":"electrical.naviop.switches.2.state","state":0},"3":{"path":"electrical.naviop.switches.3.state","state":0},"4":{"path":"electrical.naviop.switches.4.state","state":0},"5":{"path":"electrical.naviop.switches.5.state","state":0},"6":{"path":"electrical.naviop.switches.6.state","state":0},"7":{"path":"electrical.naviop.switches.7.state","state":0},"8":{"path":"electrical.naviop.switches.8.state","state":0}},"fuses":{"1":{"path":"electrical.naviop.fuses.1.state","state":0},"2":{"path":"electrical.naviop.fuses.2.state","state":0},"3":{"path":"electrical.naviop.fuses.3.state","state":0},"4":{"path":"electrical.naviop.fuses.4.state","state":0},"5":{"path":"electrical.naviop.fuses.5.state","state":0},"6":{"path":"electrical.naviop.fuses.6.state","state":0},"7":{"path":"electrical.naviop.fuses.7.state","state":0},"8":{"path":"electrical.naviop.fuses.8.state","state":0}}}}
Mar 11 09:22:53 ReferenceError: deviceAddress is not defined at
/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:427:64 at
Array.forEach (<anonymous>) at Timeout.sendUpdate [as _onTimeout]
(/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:426:17)
at listOnTimeout (internal/timers.js:557:17) at processTimers
(internal/timers.js:500:7)
Mar 11 09:22:54 ReferenceError: deviceAddress is not defined at
/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:427:64 at
Array.forEach (<anonymous>) at Timeout.sendUpdate [as _onTimeout]
(/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:426:17)
at listOnTimeout (internal/timers.js:557:17) at processTimers
(internal/timers.js:500:7)
Mar 11 09:22:55 ReferenceError: deviceAddress is not defined at
/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:427:64 at
Array.forEach (<anonymous>) at Timeout.sendUpdate [as _onTimeout]
(/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:426:17)
at listOnTimeout (internal/timers.js:557:17) at processTimers
(internal/timers.js:500:7)
Mar 11 09:22:55 2023-03-11T09:22:55.582Z signalk-naviop-plugin Received
packet msg:
{"canId":233644044,"prio":3,"src":12,"dst":32,"pgn":126208,"timestamp":"2023-03-11T09:22:55.580Z","input":[],"fields":{"Function
Code":"Command","PGN":127500,"Priority":"Leave priority unchanged","# of
Parameters":2,"list":[{"Parameter":2,"Value":0},{"Parameter":3,"Value":0},{"Parameter":0},{"Parameter":0},{"Parameter":0},{"Parameter":0}]},"description":"NMEA
- Command group function"}
Mar 11 09:22:55 2023-03-11T09:22:55.585Z signalk-naviop-plugin
n2k.fields.list:
[{"Parameter":2,"Value":0},{"Parameter":3,"Value":0},{"Parameter":0},{"Parameter":0},{"Parameter":0},{"Parameter":0}]

Mar 11 09:22:55 2023-03-11T09:22:55.587Z signalk-naviop-plugin instance:
1 state: 0
Mar 11 09:22:55 2023-03-11T09:22:55.590Z signalk-naviop-plugin Digital
switching command 126208 Instance 1 -> 0]
Mar 11 09:22:55 2023-03-11T09:22:55.592Z signalk-naviop-plugin
digiSwitch:
{"1":{"switches":{"1":{"path":"electrical.naviop.switches.1.state","state":1},"2":{"path":"electrical.naviop.switches.2.state","state":0},"3":{"path":"electrical.naviop.switches.3.state","state":0},"4":{"path":"electrical.naviop.switches.4.state","state":0},"5":{"path":"electrical.naviop.switches.5.state","state":0},"6":{"path":"electrical.naviop.switches.6.state","state":0},"7":{"path":"electrical.naviop.switches.7.state","state":0},"8":{"path":"electrical.naviop.switches.8.state","state":0}},"fuses":{"1":{"path":"electrical.naviop.fuses.1.state","state":0},"2":{"path":"electrical.naviop.fuses.2.state","state":0},"3":{"path":"electrical.naviop.fuses.3.state","state":0},"4":{"path":"electrical.naviop.fuses.4.state","state":0},"5":{"path":"electrical.naviop.fuses.5.state","state":0},"6":{"path":"electrical.naviop.fuses.6.state","state":0},"7":{"path":"electrical.naviop.fuses.7.state","state":0},"8":{"path":"electrical.naviop.fuses.8.state","state":0}}}}
Mar 11 09:22:55 2023-03-11T09:22:55.594Z signalk-naviop-plugin Updating
digiSwitch[1].switches[1].state to 0
Mar 11 09:22:55 2023-03-11T09:22:55.597Z signalk-naviop-plugin update:
{"updates":[{"values":[{"path":"electrical.naviop.switches.1.state","value":0}]}]}
Mar 11 09:22:55 2023-03-11T09:22:55.600Z signalk-naviop-plugin
handleUpdate: electrical.naviop.switches.1.state -> 0
Mar 11 09:22:55 2023-03-11T09:22:55.602Z signalk-naviop-plugin
updatePathState: electrical.naviop.switches.1.state to 0
Mar 11 09:22:55 2023-03-11T09:22:55.604Z signalk-naviop-plugin Checking
switches deviceObject:
{"1":{"path":"electrical.naviop.switches.1.state","state":0},"2":{"path":"electrical.naviop.switches.2.state","state":0},"3":{"path":"electrical.naviop.switches.3.state","state":0},"4":{"path":"electrical.naviop.switches.4.state","state":0},"5":{"path":"electrical.naviop.switches.5.state","state":0},"6":{"path":"electrical.naviop.switches.6.state","state":0},"7":{"path":"electrical.naviop.switches.7.state","state":0},"8":{"path":"electrical.naviop.switches.8.state","state":0}}
Mar 11 09:22:55 2023-03-11T09:22:55.605Z signalk-naviop-plugin Checking
switches 1: {"path":"electrical.naviop.switches.1.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.607Z signalk-naviop-plugin Checking
electrical.naviop.switches.1.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.608Z signalk-naviop-plugin
updatePathState: electrical.naviop.switches.1.state in
{"path":"electrical.naviop.switches.1.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.610Z signalk-naviop-plugin Checking
switches 2: {"path":"electrical.naviop.switches.2.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.612Z signalk-naviop-plugin Checking
electrical.naviop.switches.2.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.613Z signalk-naviop-plugin Checking
switches 3: {"path":"electrical.naviop.switches.3.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.615Z signalk-naviop-plugin Checking
electrical.naviop.switches.3.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.616Z signalk-naviop-plugin Checking
switches 4: {"path":"electrical.naviop.switches.4.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.618Z signalk-naviop-plugin Checking
electrical.naviop.switches.4.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.619Z signalk-naviop-plugin Checking
switches 5: {"path":"electrical.naviop.switches.5.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.620Z signalk-naviop-plugin Checking
electrical.naviop.switches.5.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.622Z signalk-naviop-plugin Checking
switches 6: {"path":"electrical.naviop.switches.6.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.623Z signalk-naviop-plugin Checking
electrical.naviop.switches.6.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.624Z signalk-naviop-plugin Checking
switches 7: {"path":"electrical.naviop.switches.7.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.626Z signalk-naviop-plugin Checking
electrical.naviop.switches.7.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.628Z signalk-naviop-plugin Checking
switches 8: {"path":"electrical.naviop.switches.8.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.629Z signalk-naviop-plugin Checking
electrical.naviop.switches.8.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.631Z signalk-naviop-plugin Checking
fuses deviceObject:
{"1":{"path":"electrical.naviop.fuses.1.state","state":0},"2":{"path":"electrical.naviop.fuses.2.state","state":0},"3":{"path":"electrical.naviop.fuses.3.state","state":0},"4":{"path":"electrical.naviop.fuses.4.state","state":0},"5":{"path":"electrical.naviop.fuses.5.state","state":0},"6":{"path":"electrical.naviop.fuses.6.state","state":0},"7":{"path":"electrical.naviop.fuses.7.state","state":0},"8":{"path":"electrical.naviop.fuses.8.state","state":0}}
Mar 11 09:22:55 2023-03-11T09:22:55.633Z signalk-naviop-plugin Checking
fuses 1: {"path":"electrical.naviop.fuses.1.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.634Z signalk-naviop-plugin Checking
electrical.naviop.fuses.1.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.636Z signalk-naviop-plugin Checking
fuses 2: {"path":"electrical.naviop.fuses.2.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.638Z signalk-naviop-plugin Checking
electrical.naviop.fuses.2.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.640Z signalk-naviop-plugin Checking
fuses 3: {"path":"electrical.naviop.fuses.3.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.641Z signalk-naviop-plugin Checking
electrical.naviop.fuses.3.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.643Z signalk-naviop-plugin Checking
fuses 4: {"path":"electrical.naviop.fuses.4.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.644Z signalk-naviop-plugin Checking
electrical.naviop.fuses.4.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.646Z signalk-naviop-plugin Checking
fuses 5: {"path":"electrical.naviop.fuses.5.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.647Z signalk-naviop-plugin Checking
electrical.naviop.fuses.5.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.649Z signalk-naviop-plugin Checking
fuses 6: {"path":"electrical.naviop.fuses.6.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.650Z signalk-naviop-plugin Checking
electrical.naviop.fuses.6.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.652Z signalk-naviop-plugin Checking
fuses 7: {"path":"electrical.naviop.fuses.7.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.653Z signalk-naviop-plugin Checking
electrical.naviop.fuses.7.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.654Z signalk-naviop-plugin Checking
fuses 8: {"path":"electrical.naviop.fuses.8.state","state":0}
Mar 11 09:22:55 2023-03-11T09:22:55.656Z signalk-naviop-plugin Checking
electrical.naviop.fuses.8.state == electrical.naviop.switches.1.state ?
Mar 11 09:22:55 2023-03-11T09:22:55.658Z signalk-naviop-plugin Switch
states:
{"1":{"switches":{"1":{"path":"electrical.naviop.switches.1.state","state":0},"2":{"path":"electrical.naviop.switches.2.state","state":0},"3":{"path":"electrical.naviop.switches.3.state","state":0},"4":{"path":"electrical.naviop.switches.4.state","state":0},"5":{"path":"electrical.naviop.switches.5.state","state":0},"6":{"path":"electrical.naviop.switches.6.state","state":0},"7":{"path":"electrical.naviop.switches.7.state","state":0},"8":{"path":"electrical.naviop.switches.8.state","state":0}},"fuses":{"1":{"path":"electrical.naviop.fuses.1.state","state":0},"2":{"path":"electrical.naviop.fuses.2.state","state":0},"3":{"path":"electrical.naviop.fuses.3.state","state":0},"4":{"path":"electrical.naviop.fuses.4.state","state":0},"5":{"path":"electrical.naviop.fuses.5.state","state":0},"6":{"path":"electrical.naviop.fuses.6.state","state":0},"7":{"path":"electrical.naviop.fuses.7.state","state":0},"8":{"path":"electrical.naviop.fuses.8.state","state":0}}}}
Mar 11 09:22:56 ReferenceError: deviceAddress is not defined at
/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:427:64 at
Array.forEach (<anonymous>) at Timeout.sendUpdate [as _onTimeout]
(/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:426:17)
at listOnTimeout (internal/timers.js:557:17) at processTimers
(internal/timers.js:500:7)
Mar 11 09:22:57 ReferenceError: deviceAddress is not defined at
/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:427:64 at
Array.forEach (<anonymous>) at Timeout.sendUpdate [as _onTimeout]
(/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:426:17)
at listOnTimeout (internal/timers.js:557:17) at processTimers
(internal/timers.js:500:7)

**Comment by htool** [comment]
Did you save/submit the plugin config?
Do you have a can0 device (ifconfig)?

**Comment by KNXfriend** [comment]
Hi Hans,

yes, I submitted the config.

As far as I understand I have a can0 device.

I get all data from N2K into SignalK and even the switch commands from
MFD comes into the databrowser.

electrical.naviop.switches.1.state //

0


	03/11 10:22:55 	signalk-naviop-plugin

The state changes, like expected to 1 and 0 with each button press.

But with my limited understanding it seems, that the feedback to the MFD
is not coming.

Am 11/03/2023 um 11:47 schrieb Hans:

**Comment by KNXfriend** [comment]
It´s a Victron Cerbo GX with Venus large OS.


Hi Hans,


yes, I submitted the config.

As far as I understand I have a can0 device.

I get all data from N2K into SignalK and even the switch commands from
MFD comes into the databrowser.

electrical.naviop.switches.1.state

0


	03/11 10:22:55 	signalk-naviop-plugin

The state changes, like expected to 1 and 0 with each button press.

But with my limited understanding it seems, that the feedback to the MFD
is not coming.

Am 11/03/2023 um 11:47 schrieb Hans:

**Comment by htool** [comment]
What do you have under 'Server -> Data connections -> canbus'?
Can you try the latest version of signalk-naviop-plugin?

**Comment by KNXfriend** [comment]
Hello Hans,

update is installed now.

Server log still records a lot:

Mar 12 10:36:33 ReferenceError: deviceAddress is not defined at
/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:427:64 at
Array.forEach (<anonymous>) at Timeout.sendUpdate [as _onTimeout]
(/data/conf/signalk/node_modules/signalk-naviop-plugin/index.js:426:17)
at listOnTimeout (internal/timers.js:557:17) at processTimers
(internal/timers.js:500:7)


I don´t find directly the canbus entry. Do you mean, that the ID should
be named canbus?

Connections
ID 	Data Type 	Enabled 	Logging
n2k-on-ve.can-socket
NMEA2000

Yes

No

Data Type
NMEA2000
Enabled
Logging
ID
NMEA 2000 Source
Interface
Example: can0
Use Can NAME in source data
Override timestamps

No filters defined.





Am 11/03/2023 um 15:44 schrieb Hans:

**Comment by htool** [comment]
So it has a problem setting up the canbus interface.
n2k-on-ve.can-socket is the entry to look into.
I'm trying to get some info from victron on this. You can also join the community on slack: signalk-dev.slack.com

**Comment by htool** [comment]
Try 'can1' as interface name.

**Comment by htool** [comment]
If that doesn't work, try 'can0'.

**Comment by KNXfriend** [comment]
I added a new Data Connection with the ID "canbus" and named the
interface can1.

Now the plugin workes fine. The MFD gets the status and the log stays clean.

Thank you very much!


I am not sure, if this configuration with two connections on the same
physical interface is ok. But currently everything seems to be working.

Am 12/03/2023 um 11:52 schrieb Hans:

**Comment by KNXfriend** [comment]
Talking about slack.

I am strugelling with the login.
How to acces your community? With my emailadress ***@***.***?

Slack always says, that no accout is existing.
When I try to make me a new account, seems that slack assumes I want to
open a new community?

How to access your community?

Am 12/03/2023 um 11:48 schrieb Hans:

**Comment by htool** [comment]
https://slack.com/help/articles/212675257-Join-a-Slack-workspace#join-a-workspace explains how to join.
The workspace name is 'signalk-dev'.

Your setup still seems strange. Setting up a new interface shouldn't be needed.
Could you try to remove the connection and use 'can1' as name of the interface in the plugin config?

**Comment by KNXfriend** [comment]
Config might be strange.
But only put can1 in the connection with the id n2k-on-ve.can-socket
leads to a happy plugin (no suspicious entries in the log) but the MFD
gets no updates.

With the additional connection with the id canbus and can1 leads to
complete succes. I can control my actuators and send status back.

All the other data in my N2K network is as well visible in the databrowser.


Your slack link brings me partially further. But now slack says that I
have no invitation.


Am 12/03/2023 um 12:35 schrieb Hans:

**Comment by htool** [comment]
What's your slack username/email?

**Comment by htool** [comment]
Closing this after some updates on the plugin. Feel free to reopen if the issue persists.
